[versions]

# ====== 编译配置版本 ======
compileSdk = "35"
minSdk = "24"
targetSdk = "35"
buildVersion = "35.0.0"
versionCode = "3010"
versionName = "3.0.1.0"

# ====== Java 版本配置 ======
java-version = "21"
java-source-compatibility = "21"
java-target-compatibility = "21"
kotlin-jvm-target = "21"

# Kotlin 编译器扩展版本（Compose 相关）
kotlin-compiler-extension = "1.5.3"

# Kotlin 序列化插件版本
kotlin-serialization = "2.1.0"  # 与 Kotlin 版本保持一致

# ====== Gradle 插件版本 ======
agp = "8.9.0"
kotlin-gradle-plugin = "2.1.0"

# ====== 字节码技术 ======
javassist="3.30.2-GA"
asm="2.0"
byte-buddy = "1.14.1"

# ====== Hilt 版本 ======
dagger = "2.57.2"
hilt = "2.57.2"
hilt-plugin = "2.57.2"
androidx-hilt = "1.3.0"

# ====== AndroidX 和 Kotlin 版本 ======
kotlin = "2.1.0"
jvm-version = "21"
coreKtx = "1.10.1"
ktcoroutines = "1.8.0"
multidex = "2.0.1"

# ====== 测试版本 ======
junit = "4.13.2"
junit-ext = "1.1.5"
espressoCore = "3.5.1"
databinding = "8.1.0"

# ====== Compose 版本 ======
activityCompose = "1.8.1"
activity-ktx = "1.8.0"
composeBom = "2024.04.01"
composeMaterial3 = "1.2.0"

# ====== 网络库版本 ======
okhttp = "4.11.0"
gson = "2.8.6"
retrofit2 = "2.9.0"
kotlinx-serialization = "1.6.0"

# ====== 其他库版本 ======
commons-csv = "1.9.0"
live-event-bus = "1.8.0"

# ====== UI 组件版本 ======
appcompat = "1.6.1"
material = "1.10.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
vectordrawable = "1.0.1"
recyclerview = "1.0.0"
cardview = "1.0.0"
navigation = "2.5.1"
paging = "3.0.0"

# ====== 架构组件版本 ======
lifecycle = "2.5.1"
glide = "4.14.2"
datastore = "1.0.0"
room = "2.4.0"
work = "2.7.1"

# ====== RxJava 版本 ======
rx3-android = "3.0.2"
rx3-java = "3.1.5"
rx2-android = "2.1.0"
rx-2java = "2.1.0"
rx-2binding = "2.1.0"

# ====== auto-service,javapoet ,guava版本 ======
auto-service="1.1.1"
annotation-api="1.3.2"
javapoet="1.13.0"
guava="32.1.3-android"

#xlog
xlog = "1.11.0"



[libraries]
# ====== Gradle 插件类路径 ======
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
hilt-gradle-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt-plugin" }

# ====== Kotlin 相关 ======
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-ktx ={ group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx"}
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "ktcoroutines" }
kotlin-stdlib= { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect= { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

# ====== 字节码技术 ======
javassist= { group = "org.javassist", name = "javassist", version.ref = "javassist" }

# ====== 测试相关 ======
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit-ext = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# ====== Compose 相关 ======
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-composeui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }

# ====== 生命周期相关 ======
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-ifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle" }
androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }

# ====== DataBinding 相关 ======
androidx-databinding-runtime = { group = "androidx.databinding", name = "databinding-runtime", version.ref = "databinding" }
androidx-databinding-common = { group = "androidx.databinding", name = "databinding-common", version.ref = "databinding" }

# ====== 网络相关 ======
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# ====== 其他库 ======
commons-csv = { group = "org.apache.commons", name = "commons-csv", version.ref = "commons-csv" }
live-event-bus = { group = "io.github.jeremyliao", name = "live-event-bus-x", version.ref = "live-event-bus" }

# ====== Retrofit 相关 ======
retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }
retrofit2-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit2" }
retrofit2-adapter-rxjava3 = { group = "com.squareup.retrofit2", name = "adapter-rxjava2", version.ref = "retrofit2" }

# ====== RxJava 相关 ======
rx3-android = { group = "io.reactivex.rxjava3", name = "rxandroid", version.ref = "rx3-android" }
rx3-java = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rx3-java" }
rx2-android = { group = "io.reactivex.rxjava2", name = "rxandroid", version.ref = "rx2-android" }
rx2-java = { group = "io.reactivex.rxjava2", name = "rxjava", version.ref = "rx-2java" }
rx2-binding = { group = "com.jakewharton.rxbinding2", name = "rxbinding", version.ref = "rx-2binding" }

# ====== UI 组件相关 ======
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

# ====== 图片加载相关 ======
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# ====== 数据存储相关 ======
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }

# ====== Room 数据库相关 ======
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "droom-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# ====== Dagger 相关 ======
dagger = { group = "com.google.dagger", name = "dagger", version.ref = "dagger" }
dagger-compiler = { group = "com.google.dagger", name = "dagger-compiler", version.ref = "dagger" }
dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger" }
dagger-android-processor = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }

# ====== Hilt 相关 ======
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
# ======Jetpack Hilt 相关 ======
androidx-hilt-lifecycle-viewmodel= { group = "androidx.hilt", name = "hilt-lifecycle-viewmodel", version.ref = "androidx-hilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidx-hilt" }

# ====== WorkManager 相关 ======
androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }

# ====== auto-service======
auto-service = { group = "com.google.auto.service", name = "auto-service", version.ref = "auto-service" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
guava-android = { group = "com.google.guava", name = "guava", version.ref = "guava" }
javax-annotation-api= { group = "javax.annotation", name = "javax.annotation-api", version.ref = "annotation-api" }

#xlog
xlog = { group = "com.elvishew", name = "xlog", version.ref = "xlog" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-gradle-plugin" }
jetbrains-kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }  # 添加这行
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-gradle-plugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-plugin" }
jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
